//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspisanie
    {
        public int id { get; set; }
        public int NomerYroka { get; set; }
        public int Kabinet { get; set; }
        public int DisciplinaID { get; set; }
        public int TeacherID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Disciplini Disciplini { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
