//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersCurses
    {
        public int id { get; set; }
        public int idTeacher { get; set; }
        public int idCurse { get; set; }
        public int Complete { get; set; }
    
        public virtual Curse Curse { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
